version: '3.7'

services:
  mongodb:
    container_name: sweethymns-mongodb
    image: bitnami/mongodb:4.2.5
    environment:
      MONGODB_EXTRA_FLAGS: --setParameter diagnosticDataCollectionEnabled=false
      MONGODB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    networks:
      sweethymns-net:
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/bitnami/mongodb/data/db:delegated

  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sweethymns-strapi
    depends_on:
      - mongodb
    environment:
      DATABASE_NAME: ${MONGODB_DATABASE}
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      DATABASE_USERNAME: ${MONGODB_USERNAME}
      DATABASE_PASSWORD: ${MONGODB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - sweethymns-net
    ports:
      - '1337:1337'
    restart: always

networks:
  sweethymns-net:
